version: 2.4.0

#This is used for plugin internal identification.
#Please make sure the value is unique among all the types of dragons
unique_name: 'default'

display_name: 'Ender Dragon'

#In "weight" mode, this(priority) will be ignored.
#In "pc" mode, dragon with higher priority will be judged earlier
priority: -32768

#the chance of spawning a special ender dragon
#Now you can also enter a double here (unit:%)
#You shouldn't add "%".
spawn_chance: 100

#the icon that represents this dragon in gui view
icon:
  ==: org.bukkit.inventory.ItemStack
  type: APPLE
  amount: 1
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '§rNormal Dragon'

#MC1.19:
#icon:
#  ==: org.bukkit.inventory.ItemStack
#  v: 3105
#  type: APPLE
#  amount: 1
#  meta:
#    ==: ItemMeta
#    meta-type: UNSPECIFIC
#    display-name: '{"text":"Normal Dragon"}'

#the format of gui this dragon will use(chosen in file view.yml,multiple dragons can share the same one)
drop_gui: default_gui

#please enter a double that above 0
#Valid example: “100”,“1000.0”,“200.00” etc.
#TIPS: The max_health of native ender-dragon is 200.
max_health: 200

#the health of ender-dragon when it spawns
#please enter a double that above 0
#don't make it above the "max_health"
spawn_health: 200

# the least interval time between injuries (unit:tick, 1tick=0.05s)
# only supports integer value
no_damage_tick: 10

#please enter an integer here
#TIPS: In native mc,the first ender dragon drops 12000 exp,afterwards 500 exp per dragon
exp_drop: 500

dragon_egg_spawn:
  #the chance of spawning a dragon egg when this dragon died
  #enter an integer or a double (from 0 to 100)(unit:%)
  chance: 0

  #the dragon-egg spawn delay after this dragon died
  #please enter an integer that above 0 (unit:tick,20ticks=1 second)
  #Spawning an egg after the restoration of exit portal can avoid some trouble
  delay: 410

  #the position where the dragon egg spawns
  x: 0
  y: 70
  z: 0

#allow double and negative value
armor_modify: 0

#allow double and negative value
armor_toughness_modify: 0

#the health-regain amount every second when the ender-dragon is healed by ender-crystal(Native: 2.0 per second)
crystal_heal_speed: 2.0

#"none" represents not glowing; "random" is also optional
#enable color: AQUA,BLACK,BLUE,DARK_AQUA,DARK_BLUE,DARK_GRAY,DARK_GREEN,DARK_PURPLE,DARK_RED,GOLD,GRAY,GREEN,LIGHT_PURPLE,RED,WHITE,YELLOW
glow_color: none

attack:
  #the damage modify when this dragon attacks player with body or limb (allow double and negative value)
  damage_modify: 0

  #the effect give to player when this ender dragon attacks player with body or limb
  #the format is the same as effect_cloud.potion
  potion_effect:
    - ''
    - ''
    - ''

  # the effect give to player when this ender dragon attacks player with body or limb
  # format: (<type>: seconds)
  extra_effect:
    fire: 0
    # "freeze" can only be used in server greater than or equal to version 1.17
    freeze: 0


#dragon recover health when cause damage to other entity
#suck_amount = real_damage * <rate>(auto regard as "%") + <basic_amount>
suck_blood:
  enable: false

  #unit: %
  rate: 0

  #allow double
  base_amount: 0

  #whether only trigger when dragon attack the player
  only_player: true

bossbar:
  #enable:BLUE,GREEN,RED,PINK,PURPLE,WHITE,YELLOW
  color: pink

  #enable:SOLID,SEGMENTED_6,SEGMENTED_10,SEGMENTED_12,SEGMENTED_20
  style: 'SOLID'

  # [true/false]
  create_frog: true
  darken_sky: true
  play_boss_music: true

effect_cloud:
  #enter a double that above 0
  original_radius: 5

  #how many blocks it's radius will enlarge per second
  expand_speed: 0.1

  #enter an integer that above 0 (unit: second)
  duration: 30

  #RGB module,example:'255:255:0' (yellow)
  #"none" represents original type
  color: none

  #please follow the format: '<potion> <duration> <level>'
  #please enter an integer that above 0 at "duration"(unit:second)
  #please enter an integer (from 1 to 256) at "level"
  #Some potion's name differs from that in mc native command,here are all the potions you can use:
  #ABSORPTION,BAD_OMEN,BLINDNESS,CONDUIT_POWER,CONFUSION,DAMAGE_RESISTANCE,DARKNESS,DOLPHINS_GRACE
  #FAST_DIGGING,FIRE_RESISTANCE,GLOWING,HARM,HEAL,HEALTH_BOOST,HERO_OF_THE_VILLAGE,HUNGER
  #INCREASE_DAMAGE,INVISIBILITY,JUMP,LEVITATION,LUCK,NIGHT_VISION,POISON,REGENERATION,SATURATION
  #SLOW,SLOW_DIGGING,SLOW_FALLING,SPEED,UNLUCK,WATER_BREATHING,WEAKNESS,WITHER
  potion:
    - 'harm 60 2'
    - 'BLINDNESS 10 1'

#All the settings below can be disabled with a "[]".(Ex: spawn_cmd: [] )

#commands that server will run when this dragon spawn
#Attention: Please DON'T add “/” at the beginning of each command!
spawn_cmd:
  - ''
  - ''
  - ''

#commands that server will run when this dragon been killed(exclude '/kill')
#You can use %player% respective the name of killer
#if plugin can't find who kill the dragon,commands that contain '%player%' won't be performed
#Example: - 'give %player% apple 1'
death_cmd:
  - ''
  - ''
  - ''

#Message send to everyone when this dragon spawn
#"%times" respective the ordinal number of this dragon
spawn_broadcast_msg:
  - '§aDragon No.%times% has spawned.'
  - ''

#Message send to everyone when this dragon is killed(exclude '/kill')
#"%times" respective the ordinal number of this dragon
#You can use {damage_statistics} to send "Dragon Slaying Report" with hover text.
#The plugin will try to find the killer as far as possible.If killer can't be found, %player% will be replaced with the 'dragon.no_killer' in language file
death_broadcast_msg:
  - '§bDragon No.%times% has been killed by %player%'
  - 'Rewards has been distributed! {damage_statistics}'
  - ''

#message that will be sent to the killer(if he/she can be found)
#"%times" respective the ordinal number of this dragon
msg_to_killer:
  - '§bCongratulations, You have been the dragon slayer!'
  - ''
  - ''

reward_dist:
  # enable: [all,drop,killer,pack,rank,termwise]
  # all: Give to all participants in dragon slaying.
  # drop: Dropped item, players can grab it casually.
  # killer: Only give to the final killer.
  # pack: Pack all items that trigger drop and distribute them to players weighted based on their damage percentage.
  # rank: Strictly based on player damage ranking, give the top few players with the highest damage.
  # termwise: Assign items that trigger the drop ONE BY ONE to the player based on the weighted proportion of damage.
  type: killer
  drop:
    # Whether the dropped item glows.
    # Refer to the previous 'glow_color' for configuration method
    glow: green
  pack:
    # the number of player(s) can be selected at most
    max_num: 1
  rank:
    # Top few can receive rewards
    max_num: 1

special_loot:
  # You can add more entries with DIFFERENT name according to the format.
  # If such target not exists, this option will be ignored.
  # type: exp, command
  loot1:
    # [true/false]
    enable: false
    type: command
    # %attacker% -> all participants in dragon slaying
    target: "%attacker%"
    # %player% -> target, %damage% -> this player's damage to EnderDragon
    data:
      - 'give %player% stone 1'
      - 'ed action %player% tell: This is a guaranteed reward.'
  loot2:
    enable: false
    type: command
    # %attacker_top_<rank>% -> the player with exactly this rank
    target: "%attacker_top_1%"
    data:
      - 'ed action %player% tell: You are the one who causes the highest damage!'
      - 'ed action %player% tell: Your damage: %damage%'
  loot_exp1:
    enable: false
    type: exp
    target: "%attacker_top_2%"
    data:
      # add 20 exp for the rank_2 player
      amount: 20
