#配置文件版本，请勿修改
version: 2.3.0

#可选: 'Chinese','English'
lang: 'English'

#可选: 'Disable'（不启用）,'ChatBox'（聊天栏）,'SubTitle'（副标题）,'ActionBar'（状态栏）
damage_visible_mode: ActionBar

damage_statistics:
  # 显示伤害排名前几的玩家
  limit: 10

#可选: 'weight','pc' ('edge' 已不再使用！)
#'weight'(edge): 使用权重来决定每次生成哪条龙（包括默认龙default）
#'pc': 即“优先级+概率”，插件会先尝试生成（按照其设定的概率）优先级最高的龙，如果失败则尝试下一条，如果都失败就生成默认龙default
#注意，在pc模式下，默认龙是用来兜底的，也就是说，如果你使用的是该模式，给默认龙设置再高的优先级都无效
special_dragon_jude_mode: 'weight'

#格式: '名字:权重'
#这里的名字与文件名一一对应，如果你要增加新的龙配置，需要在plugins/EnderDragon/setting中新建一个"名字.yml"文件，然后在这里加上一项：- '名字:权重'
#权重需为正整数
dragon_setting_file:
  - 'default:5'
  - 'special:5'

#自动复活末影龙
auto_respawn:
  # 你可以按格式添加更多条目，但是名称不能重复
  task1:
    #是否启用: [true/false]
    enable: false
    #对应的末地世界名字
    world_name: world_the_end
    #复活时间
    # minute:30            表示每30分钟复活
    # hour:4               表示每4小时复活
    # day:1,00:00          表示每天00:00复活
    # day:10,14:30         表示每10天的14:30复活
    # week:6,22:00         表示每周6的22:00复活
    # week:7,09:00         表示每周周日的09:00复活
    # month:8,11:43        表示每月8号的11:43复活
    # year:200,00:00       表示每年第200天的00:00复活
    respawn_time: 'day:10,22:00'
  task_2:
    enable: false
    world_name: world_the_end
    respawn_time: 'week:7,20:00'


#respawn_cd采用倒计时，精确到秒，采用独立的系统，具体配置使用 "/ed respawn_cd" 系列指令设置
#上方的"auto_respawn.invulnerable"同样作用于此
respawn_cd:
  enable: true

#如果设置为true，玩家（生存模式）将无法破坏自动复活末影龙时放置的水晶（被破坏则复活被中止）
crystal_invulnerable: false
#如果设置为true，玩家手动放置末地水晶将无法复活末影龙，但不影响末地水晶的合成、放置
resist_player_respawn: false
#如果设置为true，玩家无法用玻璃瓶收集龙息
resist_dragon_breath_gather: false
#指令/ed drop gui 打开的默认主页面
main_gui: main

#以下世界中生成的末影龙将不被插件监听
blacklist_worlds:
  - 'world'
  - 'world_nether'

#由以下原因生成的末影龙不被插件监听
#常用选项：COMMAND(原版summon指令生成),CUSTOM(别的插件生成的),DEFAULT(自然生成，包括玩家放置水晶复活的)
#你可以在这里找到所有生成原因：
#https://bukkit.windit.net/javadoc/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
#写法示例: [COMMAND,CUSTOM]
blacklist_spawn_reason: []

#可选: [default/nbt/advanced]
item_format:
  reward: default

#是否hook其他插件
hook_plugins:
  MythicLib: true

#是否启用脚本拓展
#由于涉及到依赖加载，此项配置变更只有重启服务器后才生效
expansion:
  groovy: false

#调试模式[true/false]
debug: false

#请勿修改以下配置，除非你知道你在做什么
advanced_setting:
  # 在一些mohist端中，世界环境类型可能会获取错误，这会影响复活末影龙功能
  # 设置该项为true并重启服务器将尝试修复
  world_env_fix: false
  save_respawn_status: false
  save_bossbar: false
  # to do: 允许在非末地环境使用/ed spawn或respawn复活末影龙
  # can_spawn_not_the_end: false
  backslash_split:
    reward: false